id: IEF0B0F57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T17:43:24+00:00'
last_modified: '2022-06-07T15:08:11.079013+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24156
  title: མངོན་བརྗོད་འཆི་མེད་མཛོད་ཀྱི་རྒྱ་ཆེར་འགྲེལ་པ་འདོད་འཇོའི་བ་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    916D:
      image_group_id: I1CZ2145
      title: ''
      total_pages: 740
      order: 1
      base_file: 916D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
