id: IEF0B0F57
legacy_id: P001783
ocr_import_info:
  bdrc_scan_id: W24156
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T17:38:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:25:05.535205+00:00'
last_modified: 2022-09-02 13:26:13.203526
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24156
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24156
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་བརྗོད་འཆི་མེད་མཛོད་ཀྱི་རྒྱ་ཆེར་འགྲེལ་པ་འདོད་འཇོའི་བ་མོ།
  author: སི་ཏུ་ཆོས་ཀྱི་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.6476203139027858
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1CZ2145:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2145
      total_pages: 740
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2145.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6476203139027858
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
