id: P001783
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W24156
  title: མངོན་བརྗོད་འཆི་མེད་མཛོད་ཀྱི་རྒྱ་ཆེར་འགྲེལ་པ་འདོད་འཇོའི་བ་མོ།
  author: ''
  volumes:
    ad616a6a04bd4358acd6b9f891d168a8:
      image_group_id: I1CZ2145
      title: ''
      volume_number: 1
      total_pages: 740
      base_file: v001.txt
